[package]
name = "delua"
version = "0.1.0"
edition = "2018"

[dependencies]
byteorder = "1.4.3"
bytestream = "0.4.1"
env_logger = "0.8.3"
itertools = "0.10.0"
log = "0.4.14"
petgraph = "0.5.1"
shrinkwraprs = "0.3.0"
structopt = "0.3.21"
